version: '3.8'
services:
  web:
    build: .
    container_name: ninja-koans-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development

  cli:
    build: .
    container_name: ninja-koans-cli
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    entrypoint: ["sh", "-c", "npm install && tail -f /dev/null"]
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
